### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Masterzach32** [team401/2017-Robot-Code#8]
What license, if any, should we use for the robot code?

**Comment by PChild** [comment]
GNU GPLv3. It's been our standard license for several years. Do we have any
compatibility issues with 3rd party libs?

**Comment by Masterzach32** [comment]
Strongback uses the MIT license while GradleRIO uses Apache License v2.0

**Comment by PChild** [comment]
Apache and MIT are both permissive. Any unmodified parts of code under
those should keep those, modified code we can go to GPLv3.
